version: "3.9"
services:
  justwatch-api:
    image: justwatch-api:latest
    build: .
    container_name: justwatch-api
    restart: unless-stopped
    environment:
      - UVICORN_PORT=8000
    ports:
      - 5031:8000
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
networks:
  default:
    name: justwatch-api-network
    driver: bridge
